install.packages('dplyr')
install.packages('plyr')
install.packages('writexl')
library(writexl)
library(dplyr)
library(plyr)
nomes<-select(nomespossiveis,arkId,fullName,birthLikeDate,fatherFullName,motherFullName,parentFullNames)
nomes
nomes2<-arrange(nomes,birthLikeDate)
nomes2
write_xlsx(nomes2,path="C:/Users/f0fp1107/Desktop/nomespossiveis.xlsx")